# Generated by Django 5.0.14 on 2025-11-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="code_snippet",
            field=models.TextField(blank=True, null=True),
        ),
    ]
