# Generated by Django 5.0.14 on 2025-11-29 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_code_snippet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="code_snippet",
        ),
        migrations.RemoveField(
            model_name="project",
            name="content",
        ),
        migrations.CreateModel(
            name="ProjectBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Text"), ("code", "Code")], max_length=10
                    ),
                ),
                ("value", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
