# Generated by Django 5.0.14 on 2025-11-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
