# Generated by Django 5.0.14 on 2025-11-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
